package Visao;

import Controlo.CriancaDao;
import Controlo.EventoDao;
import Controlo.Validacao;
import Modelo.Crianca;
import Modelo.Evento;
import javafx.scene.control.RadioButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Helia
 */
public class TelaCadastro extends javax.swing.JFrame {
    Evento s;
     Crianca f;
       DefaultTableModel mod;
       String testeid;
    private int id;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        textFieldSemFoco();
        mostrarTabela();
        mostrarTabelEventos();
       
        
   
    }
    
     void alerta(String s){
        JOptionPane.showMessageDialog(null, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelapelido = new javax.swing.JLabel();
        jLabelnome = new javax.swing.JLabel();
        jLabelnascimento = new javax.swing.JLabel();
        jLabelmorada = new javax.swing.JLabel();
        jLabelnacionalidade = new javax.swing.JLabel();
        jTextFieldapelido = new javax.swing.JTextField();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldnascimento = new javax.swing.JTextField();
        jTextFieldmorada = new javax.swing.JTextField();
        jTextFieldnacionalidade = new javax.swing.JTextField();
        jLabeldoenca = new javax.swing.JLabel();
        jLabeltelefone = new javax.swing.JLabel();
        jTextFieldtelefone = new javax.swing.JTextField();
        jLabelemail = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabelnomepai = new javax.swing.JLabel();
        jTextFieldnomepai = new javax.swing.JTextField();
        jComboBoxdoenca = new javax.swing.JComboBox<>();
        jLabelgenero = new javax.swing.JLabel();
        jRadioButtonfeminino = new javax.swing.JRadioButton();
        jRadioButtonmasculino = new javax.swing.JRadioButton();
        jLabelprofissaoPai = new javax.swing.JLabel();
        jTextFieldprofissaopai = new javax.swing.JTextField();
        jLabelnomemae = new javax.swing.JLabel();
        jTextFieldnomemae = new javax.swing.JTextField();
        jLabelprofissaomae = new javax.swing.JLabel();
        jTextFieldprofissaomae = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelfoto = new javax.swing.JLabel();
        jLabelimagem = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonTodos = new javax.swing.JButton();
        jLabelnaturalidade = new javax.swing.JLabel();
        jTextFieldnaturalidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabeldata = new javax.swing.JLabel();
        jTextFielddata = new javax.swing.JTextField();
        jLabelhora = new javax.swing.JLabel();
        jTextFieldhora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxevento = new javax.swing.JComboBox<>();
        jLabeldescricao = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonCadastrarEvento = new javax.swing.JButton();
        jButtonEditar1 = new javax.swing.JButton();
        jButtonRemover1 = new javax.swing.JButton();
        jLabelLocalDeEvento = new javax.swing.JLabel();
        jTextFieldLocalEvento = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEventos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabelassunto = new javax.swing.JLabel();
        tfassunto = new javax.swing.JTextField();
        descr = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelapelido.setText("Apelido");

        jLabelnome.setText("Nome");

        jLabelnascimento.setText("Data De Nascimento");

        jLabelmorada.setText("Morada");

        jLabelnacionalidade.setText("Nacionalidade");

        jTextFieldapelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldapelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldapelidoFocusLost(evt);
            }
        });
        jTextFieldapelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldapelidoKeyPressed(evt);
            }
        });

        jTextFieldnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnomeFocusLost(evt);
            }
        });
        jTextFieldnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnomeKeyPressed(evt);
            }
        });

        jTextFieldnascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnascimentoFocusLost(evt);
            }
        });
        jTextFieldnascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnascimentoKeyPressed(evt);
            }
        });

        jTextFieldmorada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldmoradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldmoradaFocusLost(evt);
            }
        });
        jTextFieldmorada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldmoradaKeyPressed(evt);
            }
        });

        jTextFieldnacionalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnacionalidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnacionalidadeFocusLost(evt);
            }
        });
        jTextFieldnacionalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnacionalidadeKeyPressed(evt);
            }
        });

        jLabeldoenca.setText("Doença");

        jLabeltelefone.setText("Telefone");

        jTextFieldtelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldtelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldtelefoneFocusLost(evt);
            }
        });
        jTextFieldtelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldtelefoneKeyPressed(evt);
            }
        });

        jLabelemail.setText("Email");

        jTextFieldemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldemailFocusLost(evt);
            }
        });
        jTextFieldemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldemailKeyPressed(evt);
            }
        });

        jLabelnomepai.setText("Nome do Pai");

        jTextFieldnomepai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnomepaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnomepaiFocusLost(evt);
            }
        });
        jTextFieldnomepai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomepaiActionPerformed(evt);
            }
        });
        jTextFieldnomepai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnomepaiKeyPressed(evt);
            }
        });

        jComboBoxdoenca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gastrite", "Asma", " ", " " }));
        jComboBoxdoenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxdoencaKeyPressed(evt);
            }
        });

        jLabelgenero.setText("Genero");

        jRadioButtonfeminino.setText("Feminino");
        jRadioButtonfeminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonfemininoMouseClicked(evt);
            }
        });
        jRadioButtonfeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonfemininoKeyPressed(evt);
            }
        });

        jRadioButtonmasculino.setText("Masculino");
        jRadioButtonmasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonmasculinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRadioButtonmasculinoMouseEntered(evt);
            }
        });
        jRadioButtonmasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonmasculinoKeyPressed(evt);
            }
        });

        jLabelprofissaoPai.setText("Profissao do Pai");

        jTextFieldprofissaopai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldprofissaopaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldprofissaopaiFocusLost(evt);
            }
        });
        jTextFieldprofissaopai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldprofissaopaiKeyPressed(evt);
            }
        });

        jLabelnomemae.setText("Nome do Mae");

        jTextFieldnomemae.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnomemaeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnomemaeFocusLost(evt);
            }
        });
        jTextFieldnomemae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomemaeActionPerformed(evt);
            }
        });
        jTextFieldnomemae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnomemaeKeyPressed(evt);
            }
        });

        jLabelprofissaomae.setText("Profissao do Mae");

        jTextFieldprofissaomae.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldprofissaomaeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldprofissaomaeFocusLost(evt);
            }
        });
        jTextFieldprofissaomae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldprofissaomaeKeyPressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        jLabelfoto.setText("FOTO");

        jLabelimagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(255, 153, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setForeground(new java.awt.Color(255, 153, 0));
        jButtonEditar.setText("Editar");

        jButtonRemover.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemover.setForeground(new java.awt.Color(255, 153, 0));
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonTodos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTodos.setForeground(new java.awt.Color(255, 153, 0));
        jButtonTodos.setText("Todos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTodos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelnaturalidade.setText("Naturalidade");

        jTextFieldnaturalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldnaturalidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnaturalidadeFocusLost(evt);
            }
        });
        jTextFieldnaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnaturalidadeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelgenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelapelido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jLabelmorada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnacionalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnaturalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldnome)
                    .addComponent(jTextFieldapelido)
                    .addComponent(jRadioButtonfeminino, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTextFieldmorada)
                    .addComponent(jTextFieldnacionalidade)
                    .addComponent(jTextFieldnascimento)
                    .addComponent(jRadioButtonmasculino, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTextFieldnaturalidade))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelnomepai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelprofissaoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelnomemae, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelprofissaomae, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeldoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldprofissaopai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldprofissaomae, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnomepai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnomemae, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxdoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelapelido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelnome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeltelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldapelido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelnomepai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldnomepai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldprofissaopai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelprofissaoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelnomemae, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldnomemae, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonfeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonmasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelprofissaomae, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldprofissaomae, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabeldoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxdoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Apelido", "Nome", "Data Nascimento", "Morada", "Nacionalidade", "Genero", "Telefone", "Email", "Nome do  Pai", "Profissao do Pai", "Nome da Mae", "Profissao da Mae", "Doenca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, false, true, true, true, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);

        jTabbedPane1.addTab("Cadastro de criancas", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        jLabeldata.setText("Data");

        jLabelhora.setText("Hora");

        jLabel1.setText("Tipo de Evento");

        jLabeldescricao.setText("Descricao ");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescricao);

        jButtonCadastrarEvento.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarEvento.setForeground(new java.awt.Color(255, 153, 0));
        jButtonCadastrarEvento.setText("Cadastrar");
        jButtonCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEventoActionPerformed(evt);
            }
        });

        jButtonEditar1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar1.setForeground(new java.awt.Color(255, 153, 0));
        jButtonEditar1.setText("Editar");

        jButtonRemover1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemover1.setForeground(new java.awt.Color(255, 153, 0));
        jButtonRemover1.setText("Remover");
        jButtonRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemover1ActionPerformed(evt);
            }
        });

        jLabelLocalDeEvento.setText("Local do Evento");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabelhora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeldata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFielddata)
                    .addComponent(jTextFieldhora)
                    .addComponent(jComboBoxevento, 0, 159, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeldescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalDeEvento))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jTextFieldLocalEvento))
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastrarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jButtonEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemover1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeldata, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFielddata, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabeldescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLocalDeEvento)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldhora, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxevento, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))))))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        tabelaEventos.setBackground(new java.awt.Color(245, 242, 242));
        tabelaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Hora", "Tipo de Evento", "Descricao", "Local de Evento"
            }
        ));
        tabelaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEventosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaEventos);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jTabbedPane1.addTab("Cadastro de actividades", jPanel2);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        jLabelassunto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelassunto.setText("Assunto");

        descr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descr.setText("Descricao");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(descr, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabelassunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(tfassunto))
                .addContainerGap(1083, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfassunto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelassunto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(descr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(644, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Relatorio", jPanel8);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1739, 1048));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEventosMouseClicked
        int i=tabelaEventos.getSelectedRow();
        // testeid=mod.getValueAt(i, 0).toString();

        ///  id=(Integer.parseInt(mod.getValueAt(i, 0).toString()));
        jTextFielddata.setText(mod.getValueAt(i, 1).toString());
        jTextFieldhora.setText(mod.getValueAt(i, 2).toString());
        jComboBoxevento.setSelectedItem(mod.getValueAt(i, 3).toString());
        jTextAreaDescricao.setText(mod.getValueAt(i, 4).toString());
        jTextFieldLocalEvento.setText(mod.getValueAt(i, 2).toString());
    }//GEN-LAST:event_tabelaEventosMouseClicked

    private void jButtonRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemover1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemover1ActionPerformed

    private void jButtonCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEventoActionPerformed
        inicializarEvento();
        if(EventoDao.salvar(s)){
            alerta("Gravado com sucesso");
            dispose();
            new TelaCadastro().setVisible(true);
        }
        else
        alerta("Falha na gravacao");
    }//GEN-LAST:event_jButtonCadastrarEventoActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int i=tabela.getSelectedRow();
        testeid=mod.getValueAt(i, 0).toString();

        id=(Integer.parseInt(mod.getValueAt(i, 0).toString()));
        jTextFieldapelido.setText(mod.getValueAt(i, 1).toString());
        jTextFieldnome.setText(mod.getValueAt(i, 2).toString());
        jTextFielddata.setText(mod.getValueAt(i, 3).toString());
        jTextFieldmorada.setText(mod.getValueAt(i, 4).toString());
        jTextFieldnacionalidade.setText(mod.getValueAt(i, 5).toString());
        if(mod.getValueAt(i, 6).toString().equals("Feminino"))
        jRadioButtonfeminino.setSelected(true);
        else
        jRadioButtonmasculino.setSelected(true);

        jTextFieldtelefone.setText(mod.getValueAt(i, 7).toString());
        jTextFieldemail.setText(mod.getValueAt(i, 8).toString());
        jTextFieldnomepai.setText(mod.getValueAt(i, 9).toString());
        jTextFieldprofissaopai.setText(mod.getValueAt(i, 10).toString());
        jTextFieldprofissaomae.setText(mod.getValueAt(i, 11).toString());
        jTextFieldprofissaomae.setText(mod.getValueAt(i, 12).toString());
        jComboBoxdoenca.setSelectedItem(mod.getValueAt(i, 13).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void jTextFieldnaturalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnaturalidadeKeyPressed
        Validacao.proximaField(evt, jTextFieldtelefone);
    }//GEN-LAST:event_jTextFieldnaturalidadeKeyPressed

    private void jTextFieldnaturalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnaturalidadeFocusLost
        Validacao.perderFoco(jTextFieldnaturalidade, "ex: Maputo");
    }//GEN-LAST:event_jTextFieldnaturalidadeFocusLost

    private void jTextFieldnaturalidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnaturalidadeFocusGained
        Validacao.ganharFocus(jTextFieldnaturalidade, "ex: Maputo");
    }//GEN-LAST:event_jTextFieldnaturalidadeFocusGained

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed

        if(CriancaDao.remover(CriancaDao.pesquisar(id))){
            alerta("sucesso");
            dispose();
            new TelaCadastro().setVisible(true);
        }
        else
        alerta("Falha");       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        inicializar();
        if(CriancaDao.salvar(f)){
            alerta("Gravado com sucesso");
            dispose();
            new TelaCadastro().setVisible(true);
        }
        else
        alerta("Falha na gravacao");
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldprofissaomaeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldprofissaomaeKeyPressed
        Validacao.proximaBox(evt, jComboBoxdoenca);
    }//GEN-LAST:event_jTextFieldprofissaomaeKeyPressed

    private void jTextFieldprofissaomaeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldprofissaomaeFocusLost
        Validacao.perderFoco(jTextFieldprofissaomae, "ex: Domestica");
    }//GEN-LAST:event_jTextFieldprofissaomaeFocusLost

    private void jTextFieldprofissaomaeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldprofissaomaeFocusGained
        Validacao.ganharFocus(jTextFieldprofissaomae, "ex: Domestica");
    }//GEN-LAST:event_jTextFieldprofissaomaeFocusGained

    private void jTextFieldnomemaeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomemaeKeyPressed
        Validacao.proximaField(evt, jTextFieldprofissaomae);
    }//GEN-LAST:event_jTextFieldnomemaeKeyPressed

    private void jTextFieldnomemaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomemaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomemaeActionPerformed

    private void jTextFieldnomemaeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomemaeFocusLost
        Validacao.perderFoco(jTextFieldnomemae, "ex: Vanessa");
    }//GEN-LAST:event_jTextFieldnomemaeFocusLost

    private void jTextFieldnomemaeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomemaeFocusGained
        Validacao.ganharFocus(jTextFieldnomemae, "ex: Vanessa");
    }//GEN-LAST:event_jTextFieldnomemaeFocusGained

    private void jTextFieldprofissaopaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldprofissaopaiKeyPressed
        Validacao.proximaField(evt, jTextFieldnomemae);
    }//GEN-LAST:event_jTextFieldprofissaopaiKeyPressed

    private void jTextFieldprofissaopaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldprofissaopaiFocusLost
        Validacao.perderFoco(jTextFieldprofissaopai, "ex: Motorista");
    }//GEN-LAST:event_jTextFieldprofissaopaiFocusLost

    private void jTextFieldprofissaopaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldprofissaopaiFocusGained
        Validacao.ganharFocus(jTextFieldprofissaopai, "ex: Motorista");
    }//GEN-LAST:event_jTextFieldprofissaopaiFocusGained

    private void jRadioButtonmasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonmasculinoKeyPressed
        Validacao.proximaField(evt, jTextFieldnaturalidade);
    }//GEN-LAST:event_jRadioButtonmasculinoKeyPressed

    private void jRadioButtonmasculinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonmasculinoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmasculinoMouseEntered

    private void jRadioButtonmasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonmasculinoMouseClicked
        // TODO add your handling code here:
        if(jRadioButtonmasculino.isSelected()){
            jRadioButtonfeminino.setSelected(false);
        }else
        jRadioButtonfeminino.setSelected(true);
    }//GEN-LAST:event_jRadioButtonmasculinoMouseClicked

    private void jRadioButtonfemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonfemininoKeyPressed
        // Validacao.proximoRadio(evt, jRadioButtonmasculino);
    }//GEN-LAST:event_jRadioButtonfemininoKeyPressed

    private void jRadioButtonfemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonfemininoMouseClicked
        // TODO add your handling code here:
        if(jRadioButtonfeminino.isSelected()){
            jRadioButtonmasculino.setSelected(false);
        }else
        jRadioButtonmasculino.setSelected(true);
    }//GEN-LAST:event_jRadioButtonfemininoMouseClicked

    private void jComboBoxdoencaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxdoencaKeyPressed
        Validacao.proximaButton(evt, jButtonCadastrar);
    }//GEN-LAST:event_jComboBoxdoencaKeyPressed

    private void jTextFieldnomepaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomepaiKeyPressed
        Validacao.proximaField(evt, jTextFieldprofissaopai);
    }//GEN-LAST:event_jTextFieldnomepaiKeyPressed

    private void jTextFieldnomepaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomepaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomepaiActionPerformed

    private void jTextFieldnomepaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomepaiFocusLost
        Validacao.perderFoco(jTextFieldnomepai, "ex: Carlos");
    }//GEN-LAST:event_jTextFieldnomepaiFocusLost

    private void jTextFieldnomepaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomepaiFocusGained
        Validacao.ganharFocus(jTextFieldnomepai, "ex: Carlos");
    }//GEN-LAST:event_jTextFieldnomepaiFocusGained

    private void jTextFieldemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldemailKeyPressed
        Validacao.proximaField(evt, jTextFieldnomepai);
    }//GEN-LAST:event_jTextFieldemailKeyPressed

    private void jTextFieldemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldemailFocusLost
        Validacao.perderFoco(jTextFieldemail, "ex: heliafcossa@gmail.com");
    }//GEN-LAST:event_jTextFieldemailFocusLost

    private void jTextFieldemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldemailFocusGained
        Validacao.ganharFocus(jTextFieldemail, "ex: heliafcossa@gmail.com");
    }//GEN-LAST:event_jTextFieldemailFocusGained

    private void jTextFieldtelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtelefoneKeyPressed
        Validacao.proximaField(evt, jTextFieldemail);
    }//GEN-LAST:event_jTextFieldtelefoneKeyPressed

    private void jTextFieldtelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldtelefoneFocusLost
        Validacao.perderFoco(jTextFieldtelefone, "ex: 825509040");
    }//GEN-LAST:event_jTextFieldtelefoneFocusLost

    private void jTextFieldtelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldtelefoneFocusGained
        Validacao.ganharFocus(jTextFieldtelefone, "ex: 825509040");
    }//GEN-LAST:event_jTextFieldtelefoneFocusGained

    private void jTextFieldnacionalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnacionalidadeKeyPressed
        Validacao.proximoRadio(evt, jRadioButtonfeminino);
    }//GEN-LAST:event_jTextFieldnacionalidadeKeyPressed

    private void jTextFieldnacionalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnacionalidadeFocusLost
        Validacao.perderFoco(jTextFieldnacionalidade, "ex: Mocambicana");
    }//GEN-LAST:event_jTextFieldnacionalidadeFocusLost

    private void jTextFieldnacionalidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnacionalidadeFocusGained
        Validacao.ganharFocus(jTextFieldnacionalidade, "ex: Mocambicana");
    }//GEN-LAST:event_jTextFieldnacionalidadeFocusGained

    private void jTextFieldmoradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldmoradaKeyPressed
        Validacao.proximaField(evt, jTextFieldnacionalidade);
    }//GEN-LAST:event_jTextFieldmoradaKeyPressed

    private void jTextFieldmoradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmoradaFocusLost
        Validacao.perderFoco(jTextFieldmorada, "ex: Ferroviario");
    }//GEN-LAST:event_jTextFieldmoradaFocusLost

    private void jTextFieldmoradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmoradaFocusGained
        Validacao.ganharFocus(jTextFieldmorada, "ex: Ferroviario");
    }//GEN-LAST:event_jTextFieldmoradaFocusGained

    private void jTextFieldnascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnascimentoKeyPressed
        Validacao.proximaField(evt, jTextFieldmorada);
    }//GEN-LAST:event_jTextFieldnascimentoKeyPressed

    private void jTextFieldnascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnascimentoFocusLost
        Validacao.perderFoco(jTextFieldnascimento, "ex: 18/03/2000");
    }//GEN-LAST:event_jTextFieldnascimentoFocusLost

    private void jTextFieldnascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnascimentoFocusGained
        Validacao.ganharFocus(jTextFieldnascimento, "ex: 18/03/2000");
    }//GEN-LAST:event_jTextFieldnascimentoFocusGained

    private void jTextFieldnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomeKeyPressed
        Validacao.proximaField(evt, jTextFieldnascimento);
    }//GEN-LAST:event_jTextFieldnomeKeyPressed

    private void jTextFieldnomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomeFocusLost
        Validacao.perderFoco(jTextFieldnome, "ex: Laercia Angela");
    }//GEN-LAST:event_jTextFieldnomeFocusLost

    private void jTextFieldnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnomeFocusGained
        Validacao.ganharFocus(jTextFieldnome, "ex: Laercia Angela");
    }//GEN-LAST:event_jTextFieldnomeFocusGained

    private void jTextFieldapelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldapelidoKeyPressed
        Validacao.proximaField(evt, jTextFieldnome);
    }//GEN-LAST:event_jTextFieldapelidoKeyPressed

    private void jTextFieldapelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldapelidoFocusLost
        Validacao.perderFoco(jTextFieldapelido, "ex: Cossa");
    }//GEN-LAST:event_jTextFieldapelidoFocusLost

    private void jTextFieldapelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldapelidoFocusGained
        Validacao.ganharFocus(jTextFieldapelido, "ex: Cossa");
    }//GEN-LAST:event_jTextFieldapelidoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descr;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCadastrarEvento;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEditar1;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonRemover1;
    private javax.swing.JButton jButtonTodos;
    private javax.swing.JComboBox<String> jComboBoxdoenca;
    private javax.swing.JComboBox<String> jComboBoxevento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLocalDeEvento;
    private javax.swing.JLabel jLabelapelido;
    private javax.swing.JLabel jLabelassunto;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JLabel jLabeldescricao;
    private javax.swing.JLabel jLabeldoenca;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelfoto;
    private javax.swing.JLabel jLabelgenero;
    private javax.swing.JLabel jLabelhora;
    private javax.swing.JLabel jLabelimagem;
    private javax.swing.JLabel jLabelmorada;
    private javax.swing.JLabel jLabelnacionalidade;
    private javax.swing.JLabel jLabelnascimento;
    private javax.swing.JLabel jLabelnaturalidade;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelnomemae;
    private javax.swing.JLabel jLabelnomepai;
    private javax.swing.JLabel jLabelprofissaoPai;
    private javax.swing.JLabel jLabelprofissaomae;
    private javax.swing.JLabel jLabeltelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonfeminino;
    private javax.swing.JRadioButton jRadioButtonmasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldLocalEvento;
    private javax.swing.JTextField jTextFieldapelido;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldhora;
    private javax.swing.JTextField jTextFieldmorada;
    private javax.swing.JTextField jTextFieldnacionalidade;
    private javax.swing.JTextField jTextFieldnascimento;
    private javax.swing.JTextField jTextFieldnaturalidade;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldnomemae;
    private javax.swing.JTextField jTextFieldnomepai;
    private javax.swing.JTextField jTextFieldprofissaomae;
    private javax.swing.JTextField jTextFieldprofissaopai;
    private javax.swing.JTextField jTextFieldtelefone;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaEventos;
    private javax.swing.JTextField tfassunto;
    // End of variables declaration//GEN-END:variables


private void textFieldSemFoco() {
        jTextFieldapelido.setText("ex: Cossa");
        jTextFieldnome.setText("ex: Laercia Angela");
        jTextFieldnascimento.setText("ex: 18/03/2000");
        jTextFieldmorada.setText("ex: Ferroviario");
        jTextFieldnaturalidade.setText("ex: Maputo");
        jTextFieldtelefone.setText("ex: 825509040");
        jTextFieldemail.setText("ex: heliafcossa@gmail.com");
        jTextFieldnacionalidade.setText("ex: Mocambicana");
        jTextFieldprofissaopai.setText("ex: Motorista");
        jTextFieldprofissaomae.setText("ex: Domestica");
//        jRadioButtonfeminino.setSelected(true);
//        jRadioButtonmasculino.setSelected(true);
        jTextFieldnomepai.setText("ex: Carlos");
        jTextFieldnomemae.setText("ex: Vanessa");
        
    }

     void inicializar() {
            f= new Crianca();
            f.setNome(jTextFieldnome.getText().toString().trim());
            f.setApelido(jTextFieldapelido.getText().toString().trim());
            f.setNascimento(jTextFieldnascimento.getText().toString().trim());
            f.setMorada(jTextFieldmorada.getText().toString().trim());
            f.setNacionalidade(jTextFieldnacionalidade.getText().toString().trim());
            f.setNaturalidade(jTextFieldnaturalidade.getText().toString().trim());
            f.setTelefone(jTextFieldtelefone.getText().toString().trim());
            f.setEmail(jTextFieldemail.getText().toString().trim());
            f.setNomepai(jTextFieldprofissaopai.getText().toString().trim());
            f.setProfissaopai(jTextFieldprofissaopai.getText().toString().trim());
            f.setNomemae(jTextFieldnomemae.getText().toString().trim());
            f.setProfissaomae(jTextFieldprofissaomae.getText().toString().trim());
            f.setGenero(jComboBoxdoenca.getSelectedItem().toString().trim());
            if(jRadioButtonfeminino.isSelected())
            f.setGenero(jRadioButtonfeminino.getText().toString().trim());
            if(jRadioButtonmasculino.isSelected())
            f.setGenero(jRadioButtonmasculino.getText().toString().trim());
            f.setDoenca(jComboBoxdoenca.getSelectedItem().toString().trim());
    }

    void mostrarTabela() {
      mod=(DefaultTableModel) tabela.getModel();
       
      
         for(Crianca i: CriancaDao.buscar()) {
         Object[] objecto= {i.getId(),i.getApelido(),i.getNome(),i.getNascimento(),i.getMorada(),i.getNacionalidade(),i.getGenero(),
        i.getTelefone(),i.getEmail(),i.getNomepai(),i.getProfissaopai(),i.getNomemae(),i.getProfissaomae(),i.getDoenca()
            }; 
          
          mod.addRow(objecto);
   

  }
}

    private void inicializarEvento() {
            s= new Evento();
            s.setDataevento(jTextFielddata.getText().trim());
            s.setDescricao(jTextAreaDescricao.getText().toString().trim());
            s.setHoraevento((Integer.parseInt(jTextFieldhora.getText().trim())));
            s.setLocalevento((jTextFieldLocalEvento.getText().toString().trim()));
            s.setTipoevento(jComboBoxevento.getSelectedItem().toString().trim());
        
    }

    private void mostrarTabelEventos() {
         mod=(DefaultTableModel) tabelaEventos.getModel();
       
         for(Evento i: EventoDao.buscar()) {
         Object[] objecto= {i.getDataevento(),i.getHoraevento(),i.getTipoevento(),i.getDescricao(),i.getLocalevento(),
            }; 
           mod.addRow(objecto);
    }
}
    
}